name: Trigger auto deployment for testcapppolicy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/testcapppolicy-AutoDeployTrigger-e9f48908-5091-40f8-9dc1-5c6dbfc1c1f1.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTCAPPPOLICY_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: gautamacrtest.azurecr.io
          registryUsername: ${{ secrets.TESTCAPPPOLICY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTCAPPPOLICY_REGISTRY_PASSWORD }}
          containerAppName: testcapppolicy
          resourceGroup: GauthamLabTest
          imageToBuild: gautamacrtest.azurecr.io/gnandyalapipelinesjavascriptdocker:${{ github.sha }}
          

     

